2018-10-08 10:30:55 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:30:55 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:30:55 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:30:55 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:30:55 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:30:55 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:30:56 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:30:56 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:30:56 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline` is deprecated, use `scrapy.pipelines` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:30:56 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline.images` is deprecated, use `scrapy.pipelines.images` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:30:57 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline.MySQLPipeLine',
 'qiubai_proj.image_pipeline.MyImagePipeline']
2018-10-08 10:30:57 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:30:57 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:31:01 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:31:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 289,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 31, 1, 103555),
 'log_count/INFO': 7,
 'log_count/WARNING': 4,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 30, 57, 173094)}
2018-10-08 10:31:01 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:31:51 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:31:51 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:31:51 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:31:51 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:31:51 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:31:51 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:31:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:31:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:31:52 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline` is deprecated, use `scrapy.pipelines` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:31:52 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline.images` is deprecated, use `scrapy.pipelines.images` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:31:52 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline.MySQLPipeLine',
 'qiubai_proj.image_pipeline.MyImagePipeline']
2018-10-08 10:31:52 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:31:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:31:52 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:31:52 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 289,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 31, 52, 760412),
 'log_count/INFO': 7,
 'log_count/WARNING': 4,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 31, 52, 199912)}
2018-10-08 10:31:52 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:32:19 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:32:19 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:32:19 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:32:19 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:32:19 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:32:19 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:32:19 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:32:19 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:32:19 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline` is deprecated, use `scrapy.pipelines` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:32:19 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline.images` is deprecated, use `scrapy.pipelines.images` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:32:19 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline.MySQLPipeLine',
 'qiubai_proj.image_pipeline.MyImagePipeline']
2018-10-08 10:32:19 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:32:19 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:32:20 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:32:20 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 282,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 32, 20, 298768),
 'log_count/INFO': 7,
 'log_count/WARNING': 4,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 32, 19, 757217)}
2018-10-08 10:32:20 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:45:10 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:45:10 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:45:10 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:45:10 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:45:10 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:45:10 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:45:12 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:45:12 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:45:12 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline` is deprecated, use `scrapy.pipelines` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:45:12 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline.images` is deprecated, use `scrapy.pipelines.images` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:45:12 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline.MySQLPipeLine',
 'qiubai_proj.mysql_pipeline1.MySQLPipeLine',
 'qiubai_proj.image_pipeline.MyImagePipeline']
2018-10-08 10:45:12 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:45:12 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:45:13 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.quanshuwang.com/> (referer: None)
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\spiders\books_quan.py", line 16, in parse
    request = BooksQuantag(id=1,t_name=t_name,t_info=t_name,t_createtime=datetime.datetime.now(),a_flag=1)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 56, in __init__
    self[k] = v
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'BooksQuantag does not support field: a_flag'
2018-10-08 10:45:13 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:45:13 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 282,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 45, 13, 593538),
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'log_count/WARNING': 4,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/KeyError': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 45, 12, 912334)}
2018-10-08 10:45:13 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:46:14 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:46:14 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:46:14 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:46:14 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:46:14 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:46:14 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:46:14 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:46:14 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:46:15 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:46:15 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\crawler.py", line 80, in crawl
    self.engine = self._create_engine()
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\crawler.py", line 105, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "c:\pyenv\myspider_env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\mysql_pipeline1.py", line 73
    return True
    ^
SyntaxError: 'return' outside function
2018-10-08 10:46:46 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:46:46 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:46:46 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:46:46 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:46:46 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:46:46 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:46:46 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:46:46 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:46:46 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline` is deprecated, use `scrapy.pipelines` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:46:46 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline.images` is deprecated, use `scrapy.pipelines.images` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:46:46 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline.MySQLPipeLine',
 'qiubai_proj.mysql_pipeline1.MySQLPipeLine',
 'qiubai_proj.image_pipeline.MyImagePipeline']
2018-10-08 10:46:46 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:46:46 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:46:47 [scrapy.core.scraper] ERROR: Spider error processing <GET http://www.quanshuwang.com/> (referer: None)
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\spiders\books_quan.py", line 16, in parse
    request = BooksQuantag(id=1,t_name=t_name,t_info=t_name,t_createtime=datetime.datetime.now(),a_flag=1)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 56, in __init__
    self[k] = v
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 66, in __setitem__
    (self.__class__.__name__, key))
KeyError: 'BooksQuantag does not support field: a_flag'
2018-10-08 10:46:47 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:46:47 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 289,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 46, 47, 515342),
 'log_count/ERROR': 1,
 'log_count/INFO': 7,
 'log_count/WARNING': 4,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'spider_exceptions/KeyError': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 46, 46, 595803)}
2018-10-08 10:46:47 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:48:54 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:48:54 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:48:54 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:48:54 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:48:54 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:48:54 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:48:55 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:48:55 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:48:55 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline` is deprecated, use `scrapy.pipelines` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:48:55 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py:10: ScrapyDeprecationWarning: Module `scrapy.contrib.pipeline.images` is deprecated, use `scrapy.pipelines.images` instead
  from scrapy.contrib.pipeline.images import ImagesPipeline

2018-10-08 10:48:55 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline.MySQLPipeLine',
 'qiubai_proj.mysql_pipeline1.MySQLPipeLine',
 'qiubai_proj.image_pipeline.MyImagePipeline']
2018-10-08 10:48:55 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:48:55 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 393672),
 't_flag': 1,
 't_info': '玄幻魔法',
 't_name': '玄幻魔法'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 444534),
 't_flag': 1,
 't_info': '武侠修真',
 't_name': '武侠修真'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 447526),
 't_flag': 1,
 't_info': '纯爱耽美',
 't_name': '纯爱耽美'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 452518),
 't_flag': 1,
 't_info': '都市言情',
 't_name': '都市言情'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 444534),
 't_flag': 1,
 't_info': '武侠修真',
 't_name': '武侠修真'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 447526),
 't_flag': 1,
 't_info': '纯爱耽美',
 't_name': '纯爱耽美'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 447526),
 't_flag': 1,
 't_info': '纯爱耽美',
 't_name': '纯爱耽美'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 393672),
 't_flag': 1,
 't_info': '玄幻魔法',
 't_name': '玄幻魔法'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 444534),
 't_flag': 1,
 't_info': '武侠修真',
 't_name': '武侠修真'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 393672),
 't_flag': 1,
 't_info': '玄幻魔法',
 't_name': '玄幻魔法'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 452518),
 't_flag': 1,
 't_info': '都市言情',
 't_name': '都市言情'}
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 473461),
 't_flag': 1,
 't_info': '职场校园',
 't_name': '职场校园'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 480438),
 't_flag': 1,
 't_info': '穿越重生',
 't_name': '穿越重生'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 452518),
 't_flag': 1,
 't_info': '都市言情',
 't_name': '都市言情'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 473461),
 't_flag': 1,
 't_info': '职场校园',
 't_name': '职场校园'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 473461),
 't_flag': 1,
 't_info': '职场校园',
 't_name': '职场校园'}
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 488417),
 't_flag': 1,
 't_info': '历史军事',
 't_name': '历史军事'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 492407),
 't_flag': 1,
 't_info': '网游动漫',
 't_name': '网游动漫'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 500385),
 't_flag': 1,
 't_info': '恐怖灵异',
 't_name': '恐怖灵异'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 480438),
 't_flag': 1,
 't_info': '穿越重生',
 't_name': '穿越重生'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 480438),
 't_flag': 1,
 't_info': '穿越重生',
 't_name': '穿越重生'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 488417),
 't_flag': 1,
 't_info': '历史军事',
 't_name': '历史军事'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 488417),
 't_flag': 1,
 't_info': '历史军事',
 't_name': '历史军事'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 492407),
 't_flag': 1,
 't_info': '网游动漫',
 't_name': '网游动漫'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 492407),
 't_flag': 1,
 't_info': '网游动漫',
 't_name': '网游动漫'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 500385),
 't_flag': 1,
 't_info': '恐怖灵异',
 't_name': '恐怖灵异'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 500385),
 't_flag': 1,
 't_info': '恐怖灵异',
 't_name': '恐怖灵异'}
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 514349),
 't_flag': 1,
 't_info': '科幻小说',
 't_name': '科幻小说'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 518339),
 't_flag': 1,
 't_info': '美文名著',
 't_name': '美文名著'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 514349),
 't_flag': 1,
 't_info': '科幻小说',
 't_name': '科幻小说'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 514349),
 't_flag': 1,
 't_info': '科幻小说',
 't_name': '科幻小说'}
2018-10-08 10:48:59 [scrapy.core.scraper] ERROR: Error processing {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 527324),
 't_flag': 1,
 't_info': '热门推荐',
 't_name': '热门推荐'}
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\internet\defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in process_item
    dlist = [self._process_request(r, info) for r in requests]
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\pipelines\media.py", line 80, in <listcomp>
    dlist = [self._process_request(r, info) for r in requests]
  File "C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\image_pipeline.py", line 25, in get_media_requests
    if item['image_figer'] not in G_IMAGE_SET:
  File "c:\pyenv\myspider_env\lib\site-packages\scrapy\item.py", line 59, in __getitem__
    return self._values[key]
KeyError: 'image_figer'
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 518339),
 't_flag': 1,
 't_info': '美文名著',
 't_name': '美文名著'}
2018-10-08 10:48:59 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 48, 59, 518339),
 't_flag': 1,
 't_info': '美文名著',
 't_name': '美文名著'}
2018-10-08 10:48:59 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:48:59 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 287,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 48, 59, 535293),
 'log_count/ERROR': 34,
 'log_count/INFO': 7,
 'log_count/WARNING': 4,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 48, 55, 833193)}
2018-10-08 10:48:59 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:50:28 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:50:28 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:50:28 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:50:28 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:50:28 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:50:28 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:50:29 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:50:29 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:50:29 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline1.MySQLPipeLine']
2018-10-08 10:50:29 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:50:29 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 755023),
 't_flag': 1,
 't_info': '玄幻魔法',
 't_name': '玄幻魔法'}
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 757019),
 't_flag': 1,
 't_info': '纯爱耽美',
 't_name': '纯爱耽美'}
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 756021),
 't_flag': 1,
 't_info': '武侠修真',
 't_name': '武侠修真'}
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 759014),
 't_flag': 1,
 't_info': '都市言情',
 't_name': '都市言情'}
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 762006),
 't_flag': 1,
 't_info': '职场校园',
 't_name': '职场校园'}
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 765995),
 't_flag': 1,
 't_info': '穿越重生',
 't_name': '穿越重生'}
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 767989),
 't_flag': 1,
 't_info': '历史军事',
 't_name': '历史军事'}
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 768987),
 't_flag': 1,
 't_info': '网游动漫',
 't_name': '网游动漫'}
2018-10-08 10:50:29 [root] ERROR: db_error_handle has error with {'id': 1,
 't_createtime': datetime.datetime(2018, 10, 8, 10, 50, 29, 770981),
 't_flag': 1,
 't_info': '恐怖灵异',
 't_name': '恐怖灵异'}
2018-10-08 10:50:29 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:50:29 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 412,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 50, 29, 783947),
 'item_scraped_count': 12,
 'log_count/ERROR': 9,
 'log_count/INFO': 7,
 'log_count/WARNING': 2,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 50, 29, 285281)}
2018-10-08 10:50:29 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:52:21 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:52:21 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:52:21 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:52:22 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:52:22 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:52:22 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:52:22 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:52:22 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:52:22 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline1.MySQLPipeLine']
2018-10-08 10:52:22 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:52:22 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:52:23 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:52:23 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 282,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 52, 23, 625508),
 'item_scraped_count': 12,
 'log_count/CRITICAL': 20,
 'log_count/INFO': 7,
 'log_count/WARNING': 2,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 52, 22, 985222)}
2018-10-08 10:52:23 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:52:23 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:52:23 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:24 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:55:24 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:55:24 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:55:25 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:55:25 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:55:25 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:55:25 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:55:25 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:55:25 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline1.MySQLPipeLine']
2018-10-08 10:55:25 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:55:25 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:26 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:55:26 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 289,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 55, 26, 626400),
 'item_scraped_count': 12,
 'log_count/CRITICAL': 20,
 'log_count/INFO': 7,
 'log_count/WARNING': 2,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 55, 25, 876405)}
2018-10-08 10:55:26 [scrapy.core.engine] INFO: Spider closed (finished)
2018-10-08 10:55:26 [twisted] CRITICAL: Unhandled error in Deferred:
2018-10-08 10:55:26 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 462, in _runInteraction
    conn = self.connectionFactory(self)
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 36, in __init__
    self.reconnect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 76, in reconnect
    self._connection = self._pool.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\twisted\enterprise\adbapi.py", line 429, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "c:\pyenv\myspider_env\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'LAPTOP-MRCG27VV' (using password: YES)")
2018-10-08 10:55:41 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: qiubai_proj)
2018-10-08 10:55:41 [scrapy.utils.log] INFO: Versions: lxml 4.2.4.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 18.7.0, Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)], pyOpenSSL 18.0.0 (OpenSSL 1.1.0i  14 Aug 2018), cryptography 2.3.1, Platform Windows-10-10.0.17134-SP0
2018-10-08 10:55:41 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'qiubai_proj', 'LOG_FILE': 'log/scrapy_2018_10_8.log', 'LOG_LEVEL': 'INFO', 'NEWSPIDER_MODULE': 'qiubai_proj.spiders', 'SPIDER_MODULES': ['qiubai_proj.spiders'], 'USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36'}
2018-10-08 10:55:41 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2018-10-08 10:55:41 [py.warnings] WARNING: c:\pyenv\myspider_env\lib\site-packages\scrapy\utils\deprecate.py:156: ScrapyDeprecationWarning: `scrapy.contrib.downloadermiddleware.useragent.UserAgentMiddleware` class is deprecated, use `scrapy.downloadermiddlewares.useragent.UserAgentMiddleware` instead
  ScrapyDeprecationWarning)

2018-10-08 10:55:41 [py.warnings] WARNING: C:\Users\16473\Desktop\爬虫（周\qiubai_proj\qiubai_proj\middlewares.py:106: ScrapyDeprecationWarning: Module `scrapy.contrib.downloadermiddleware.useragent` is deprecated, use `scrapy.downloadermiddlewares.useragent` instead
  from scrapy.contrib.downloadermiddleware.useragent import UserAgentMiddleware

2018-10-08 10:55:41 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'qiubai_proj.middlewares.RondomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-10-08 10:55:41 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-10-08 10:55:42 [scrapy.middleware] INFO: Enabled item pipelines:
['qiubai_proj.mysql_pipeline1.MySQLPipeLine']
2018-10-08 10:55:42 [scrapy.core.engine] INFO: Spider opened
2018-10-08 10:55:42 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-10-08 10:55:42 [scrapy.core.engine] INFO: Closing spider (finished)
2018-10-08 10:55:42 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 285,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 12669,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 10, 8, 2, 55, 42, 586717),
 'item_scraped_count': 12,
 'log_count/INFO': 7,
 'log_count/WARNING': 2,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2018, 10, 8, 2, 55, 42, 71098)}
2018-10-08 10:55:42 [scrapy.core.engine] INFO: Spider closed (finished)
